# Generated by Django 3.0.8 on 2020-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=225)),
                ('tz', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='UserTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.UserInfo')),
            ],
        ),
    ]
