# Generated by Django 3.0.8 on 2020-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200731_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
