# Generated by Django 3.0.8 on 2020-07-31 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200731_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='end_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 31, 9, 5, 41, 66384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
