# Generated by Django 3.0.8 on 2020-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200731_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
