# Generated by Django 3.0.8 on 2020-07-31 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20200731_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
