# Generated by Django 3.0.8 on 2020-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20200731_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
